package main.htmlfileLogger.web;


import java.util.List;

public class GenTabsCSS {

    public static boolean mod_html = true;
    public static final List<String> char_list = List.of("A", "B", "C", "D", "E", "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P", "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z", "AA", "AB", "AC", "AD", "AE", "AF", "AG", "AH", "AI", "AJ", "AK", "AL", "AM", "AN", "AO", "AP", "AQ", "AR", "AS", "AT", "AU", "AV", "AW", "AX", "AY", "AZ");
    public static final int line_width = 7;

    public static String getTabsStyleHeader() {
        return new StringBuilder().append(":root {\n")
                .append("  --primary-light: #e9d9ff;\n")
                .append("  --primary: #643cf5;\n")
                .append("  --greyLight: #ddd;\n")
                .append("  --greyLight-2: #c8d1f5;\n")
                .append("  --greyDark: #333;\n")
                .append("}\n")
                .append("\n")
                .append("*, *::before, *::after {\n")
                .append("  margin: 0;\n")
                .append("  padding: 0;\n")
                .append("  box-sizing: inherit;\n")
                .append("}\n")
                .append("html").append(mod_html ? "" : "_rm").append(" {\n")
                .append("  box-sizing: border-box;\n")
                .append("  font-size: 62.5%;\n")
                .append("  overflow-y: scroll;\n")
                .append("  font-family: 'Inter', sans-serif;\n")
                .append("  -webkit-font-smoothing: antialiased;\n")
                .append("  letter-spacing: .6px;\n")
                .append("  line-height: 1.4;\n")
                .append("}\n")
                .append("\n")
                .append(".container {\n")
                .append("  min-height: 100vh;\n")
                .append("  display: flex;\n")
                .append("  justify-content: center;\n")
                .append("  align-items: center;\n")
                .append("}\n")
                .append("\n")
                .append(".tab {\n")
                .append("  width: 100%;\n")
                .append("  border-radius: 1rem;\n")
                .append("  display: flex;\n")
                .append("  flex-direction: column;\n")
                .append("  align-items: center;\n")
                .append("  color: var(--greyLight);\n")
                .append("}\n")
                .append("\n")
                .append(".menu__item {\n")
                .append("  padding-bottom: .6rem;\n")
                .append("  margin: 1 1.4rem;\n")
                .append("  font-size: 1.4rem;\n")
                .append("  font-weight: 500;\n")
                .append("  cursor: pointer;\n")
                .append("}\n")
                .append("\n")
                .append(".menu__item.is-active {\n")
                .append("  color: var(--primary);\n")
                .append("}\n")
                .append(".menu__line {\n")
                .append("  position: absolute;\n")
                .append("  bottom: 0;\n")
                .append("  width: ").append(line_width).append("rem;\n")
                .append("  height: 100%;\n")
                .append("  border-bottom: 4px solid var(--primary);\n")
                .append("  z-index: 200;\n")
                .append("  pointer-events: none;\n")
                .append("  transition: all .5s ease;\n")
                .append("}\n")
                .append(".contents {\n")
//                .append("  height: 22rem;\n")
                .append("  margin: 1rem;\n")
                .append("  display: flex;\n")
                .append("  justify-content: center;\n")
                .append("  align-items: center;\n")
                .append("  overflow: hidden;\n")
                .append("}\n")
                .append(".contents__content {\n")
                .append("  width: 100%;\n")
                .append("  display: flex;\n")
                .append("  flex-direction: column;\n")
                .append("  justify-content: center;\n")
                .append("  align-items: center;\n")
                .append("  text-align: center;\n")
                .append("}\n")
                .append(".contents__content span {\n")
                .append("  color: var(--primary);\n")
                .append("  font-size: 3rem;\n")
                .append("  margin-bottom: 1.6rem;\n")
                .append("  padding: 1rem;\n")
                .append("  border-radius: 1.2rem;\n")
                .append("  background: var(--primary-light);\n")
                .append("}\n")
                .append(".contents__content h2 {\n")
                .append("  font-size: 3rem;\n")
                .append("  color: var(--greyDark);\n")
                .append("}\n")
                .append(".contents__content p {\n")
                .append("  font-size: 1.7rem;\n")
                .append("  margin: 1.6rem 0;\n")
                .append("}\n")
                .append(".contents__content button {\n")
                .append("  border: none;\n")
                .append("  outline: none;\n")
                .append("  background: none;\n")
                .append("  color: var(--primary);\n")
                .append("  font-family: inherit;\n")
                .append("  font-size: 1.4rem;\n")
                .append("  font-weight: 500;\n")
                .append("  cursor: pointer;\n")
                .append("}\n")
                .append(".contents__content button:hover {\n")
                .append("  border-bottom: 1px solid var(--primary);\n")
                .append("}\n")
                .append("\n")
                .append(".fadeUp-enter {\n")
                .append("  opacity: 0;\n")
                .append("}\n")
                .append("\n")
                .append(".fadeUp-enter-active {\n")
                .append("  animation: slide-in .3s ease-in-out forwards;\n")
                .append("  transition: opacity .3s;\n")
                .append("}\n")
                .append("\n")
                .append(".fadeUp-leave-active {\n")
                .append("  animation: slide-out .3s ease-in-out forwards;\n")
                .append("  transition: opacity  .3s;\n")
                .append("  opacity: 0;\n")
                .append("}\n")
                .append("\n")
                .append(".fadeDown-enter {\n")
                .append("  opacity: 0;\n")
                .append("}\n")
                .append("\n")
                .append(".fadeDown-enter-active {\n")
                .append("  animation: slide-in-down .3s ease-in-out forwards;\n")
                .append("  transition: opacity .3s;\n")
                .append("}\n")
                .append("\n")
                .append(".fadeDown-leave-active {\n")
                .append("  animation: slide-out-down .3s ease-in-out forwards;\n")
                .append("  transition: opacity  .3s;\n")
                .append("  opacity: 0;\n")
                .append("}\n")
                .append("\n")
                .append("@keyframes slide-in {\n")
                .append("  from {\n")
                .append("    transform: translateY(2rem);\n")
                .append("  }\n")
                .append("  to {\n")
                .append("    transform: translateY(0);\n")
                .append("  }\n")
                .append("}\n")
                .append("@keyframes slide-out {\n")
                .append("  from {\n")
                .append("    transform: translateY(0);\n")
                .append("  }\n")
                .append("  to {\n")
                .append("    transform: translateY(-2rem);\n")
                .append("  }\n")
                .append("}\n")
                .append("@keyframes slide-in-down {\n")
                .append("  from {\n")
                .append("    transform: translateY(-2rem);\n")
                .append("  }\n")
                .append("  to {\n")
                .append("    transform: translateY(0);\n")
                .append("  }\n")
                .append("}\n")
                .append("@keyframes slide-out-down {\n")
                .append("  from {\n")
                .append("    transform: translateY(0);\n")
                .append("  }\n")
                .append("  to {\n")
                .append("    transform: translateY(2rem);\n")
                .append("  }\n")
                .append("}\n").toString();
    }

    public static String getTabsStyleIndividualTabData(int noFSubTabs, String identity) {
        StringBuilder builder = new StringBuilder();

        double tabWidth = noFSubTabs * line_width;

        builder.append(".menu").append(identity).append(" {\n")
                .append("  display: flex;\n")
                .append("  justify-content: space-between;\n")
                .append("  width: ").append(tabWidth).append("rem;\n")
                .append("  /*justify-content: center;*/\n")
                .append("   position: relative;\n")
                .append("}\n");

        for (int i = 0; i < noFSubTabs; i++) {

            builder.append(".menu__item--").append(identity).append(char_list.get(i)).append(":hover {\n")
                    .append("  color: var(--primary);\n")
                    .append("}\n")
                    .append(".menu__item--").append(identity).append(char_list.get(i)).append(":hover:hover ~ .menu__line {\n")
                    .append("  transform: translateX(").append(i * tabWidth / noFSubTabs).append("rem);\n")
                    .append("  width: ").append(line_width).append("rem;\n")
                    .append("}\n");

            builder.append(".menu__line.").append(identity).append(char_list.get(i)).append(" {\n")
                    .append("  transform: translateX(").append(i * tabWidth / noFSubTabs).append("rem);\n")
                    .append("  width: ").append(line_width).append("rem;\n")
                    .append("}\n");
        }

        builder.append(".menu").append(identity).append("::after {\n")
                .append("  content: '';\n")
                .append("  position: absolute;\n")
                .append("  width: inherit;\n")
                .append("  bottom: 0;\n")
                .append("  left: 0;\n")
                .append("  height: 1px;\n")
                .append("  background: var(--greyLight-2);\n")
                .append("}\n");

        return builder.toString();
    }

    public static void main(String[] args) {
        System.out.println(getTabsStyleHeader());
        System.out.println(getTabsStyleIndividualTabData(5, ""));
    }

}
